name: 'Testing-CI'
on:
    push:
        branches:
            - master
            - main
permissions:
    contents: write
    actions: read
    checks: write
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Install packages
              run: npm ci

            - name: Run tests
              run: |
                npx jest --ci --coverage --coverageReporters json-summary --reporters=default --reporters=jest-junit

            - name: Jest Coverage Comment
              id: coverageComment
              uses: MishaKav/jest-coverage-comment@main
              with:
                coverage-summary-path: ./coverage/coverage-summary.json

            - name: Test Report
              id: testReport
              uses: dorny/test-reporter@v1
              if: success() || failure()
              with:
                name: JEST Tests
                path: ./coverage/junit.xml
                reporter: jest-junit
                
            - name: Create a coverage badge
              uses: schneegans/dynamic-badges-action@v1.7.0
              with:
                auth: ${{ secrets.GIST_SECRET }}
                gistID: fa88c797e8e669a37852cfa474bd4c1b
                filename: coverage_badge.json
                label: Coverage
                message: ${{ steps.coverageComment.outputs.coverage }}%
                color: ${{ steps.coverageComment.outputs.color }}

            - name: Create a report badge
              uses: schneegans/dynamic-badges-action@v1.7.0
              with:
                auth: ${{ secrets.GIST_SECRET }}
                gistID: 39462aafd77c5fcbe24320b6bf4648c3
                filename: report_badge.json
                label: Tests
                message: ${{ steps.testReport.passed }}% passed, ${{ steps.testReport.failed }}% failed
                color: ${{ steps.testReport.conclusion == 'success' && 'green' || 'red' }}
